# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Build 

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: ./dist
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
       key: ${{ secrets.SSH_PRIVATE_KEY }} 
       known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }} 
      
    - uses: actions/download-artifact@master
      with:
        name: dist
        path: ./dist

    - name: Deploy with rsync
      run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:public/
